#1-3 генерация публикаций
htmlacademy-nodejs/273215-typoteka-3 pull request #3
Opened 2020-02-03 08:06 UTC by dawinn

2020-02-04 06:16 UTC, Siri0n requested changes

2020-02-04 06:16 UTC, Siri0n commented on src/service/cli/generate.js
> +    createdDate: dateFormat((getRandomInt((new Date(currentDate.getFullYear(), currentDate.getMonth() - 3, currentDate.getDate())), currentDate.getTime())), `%Y-%m-%d %H:%M:%S`),
Очень страшная строка, необходимо отрефакторить.

2020-02-04 06:16 UTC, Siri0n commented on src/utils.js
> +  return strFormat.replace(/%[YmdHMS]/g, (match) => {
Хитро. Но вообще можно было обойтись Date#toLocaleString с правильными опциями)

2020-02-04 07:40 UTC, dawinn commented on src/service/cli/generate.js
> +    createdDate: dateFormat((getRandomInt((new Date(currentDate.getFullYear(), currentDate.getMonth() - 3, currentDate.getDate())), currentDate.getTime())), `%Y-%m-%d %H:%M:%S`),
Варианты, которые приходят мне в голову, но не нравятся:
1) вытащить отдельную переменную для получения даты -3 месяца;
2) сделать функцию которая тупо отдает рандомную дату по данным условиям
3) getRandomInt((new Date(currentDate - <3 месяца как большое магическое число в миллисекундах, заданное в виде константы>), `%Y-%m-%d %H:%M:%S`)

Если есть более изящное решение,  предлагай. У меня идеи кончились.

2020-02-04 07:44 UTC, dawinn commented on src/utils.js
> +  return strFormat.replace(/%[YmdHMS]/g, (match) => {
Меня смутила необходимость выводить дату в Венгерской локали. К тому же пока не знаю насколько Node.js  связан с совместимостями браузера https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

2020-02-06 05:40 UTC, Siri0n commented on src/service/cli/generate.js
> +    createdDate: dateFormat((getRandomInt((new Date(currentDate.getFullYear(), currentDate.getMonth() - 3, currentDate.getDate())), currentDate.getTime())), `%Y-%m-%d %H:%M:%S`),
Да я бы сказал, даже две отдельных переменных. Для -3 месяца и для рандомной даты. Вложенность вызовов - это нехорошо, лучше ей не злоупотреблять. Рефакторинг её через создание промежуточных переменных - это норма. Это не изящно, но задача коммерческого программиста - писать понятный код, а не изящный.

2020-02-10 08:27 UTC, merged